name: Playwright Tests

on:
  push:
  
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: route
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Initialize database schema and seed data
      run: |
        sudo apt-get update && sudo apt-get install -y mysql-client
        echo "Waiting for MySQL to be ready..."
        for i in {1..10}; do
          mysql -h 127.0.0.1 -P 3306 -u root -p'route' -e "SELECT 1" && break || sleep 3
        done
        echo "Creating table and inserting sample data..."
        mysql -h 127.0.0.1 -P 3306 -u root -p'route' testdb <<EOF
CREATE TABLE IF NOT EXISTS dogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  breed VARCHAR(255),
  age INT
);
INSERT INTO dogs (name, breed, age) VALUES
  ('Buddy', 'Golden Retriever', 3),
  ('Max', 'Labrador', 5),
  ('Bella', 'Poodle', 2);
EOF
